# Generated by Django 3.1.5 on 2021-11-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdetails',
            name='date',
            field=models.CharField(max_length=60),
        ),
    ]
